[project]
name = "metrics-client"
version = "0.1.0"
description = "Cliente Prometheus minimal"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = []
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
